[project]
name = "github-consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "cryptography>=44.0.1",
  "fastapi[standard]>=0.115.8",
  "loguru>=0.7.3",
  "pyjwt>=2.10.1",
  "pymongo>=4.11.1",
  "python-dotenv>=1.0.1",
  "requests>=2.32.3",
]
