/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const Questions = z
  .object({
    questions: z.array(z.string()).default(null),
  })
  .strict();
export type QuestionsType = z.infer<typeof Questions>;

export const NewPrompt = z
  .object({
    thinking: z.string().default(null),
    prompt: z.string().default(null),
    summary: z.string().default(null),
  })
  .strict();
export type NewPromptType = z.infer<typeof NewPrompt>;
