/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const Chunk = z
  .object({
    text: z.string(),
    filePath: Path,
    chunkIndex: z.number().int(),
    startingLine: z.number().int(),
    endingLine: z.number().int(),
  })
  .strict();
export type ChunkType = z.infer<typeof Chunk>;

export const VectorDbSearchResult = z
  .object({
    id: z.string(),
    chunk: Chunk,
    similarityScore: z.number(),
  })
  .strict();
export type VectorDbSearchResultType = z.infer<typeof VectorDbSearchResult>;

export const RerankedScore = z
  .object({
    thinking: z.string().default(null),
    filePath: Path.default(null),
    id: z.string().default(null),
    score: z.number().default(null),
  })
  .strict();
export type RerankedScoreType = z.infer<typeof RerankedScore>;

export const RerankerResult = z
  .object({
    scores: z.array(RerankedScore).default(null),
  })
  .strict();
export type RerankerResultType = z.infer<typeof RerankerResult>;
