/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const ImplementData = z
  .object({
    description: z.string().default(null),
    purpose: z.string().default(null),
  })
  .strict();
export type ImplementDataType = z.infer<typeof ImplementData>;

export const SelectionContextResult = z
  .object({
    reasoning: z.string().default(null),
    actionToPerform: ActionToPerform.default(null),
    askClarifyingQuestions: z.boolean().default(null),
    modifiedUrls: z.array(z.string()).default(null),
    summary: z.string().default(null),
  })
  .strict();
export type SelectionContextResultType = z.infer<typeof SelectionContextResult>;
