/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const DraftStep = z
  .object({
    thinking: z.string().default(null),
    stepName: z.string().default(null),
    miniSteps: z.array(z.string()).default(null),
  })
  .strict();
export type DraftStepType = z.infer<typeof DraftStep>;

export const ExistingFileModification = z
  .object({
    modificationType: z.literal("edit_file"),
    purpose: z.string().default(null),
    thinking: z.string().default(null),
    filePath: z.string().default(null),
    whereToAdd: z.string().default(null),
    apiRequestIds: z.array(z.number().int()).default(null),
    description: z.string().default(null),
    needsSearch: z.boolean().default(null),
  })
  .strict();
export type ExistingFileModificationType = z.infer<
  typeof ExistingFileModification
>;

export const NewFileModification = z
  .object({
    modificationType: z.literal("create_file"),
    purpose: z.string().default(null),
    thinking: z.string().default(null),
    newFileDirectory: z.string().default(null),
    apiRequestIds: z.array(z.number().int()).default(null),
    description: z.string().default(null),
    needsFilePaths: z.boolean().default(null),
  })
  .strict();
export type NewFileModificationType = z.infer<typeof NewFileModification>;

export const TerminalCommandModification = z
  .object({
    modificationType: z.literal("run_command"),
    purpose: z.string().default(null),
    thinking: z.string().default(null),
    command: z.string().default(null),
  })
  .strict();
export type TerminalCommandModificationType = z.infer<
  typeof TerminalCommandModification
>;

export const GroupedSteps = z
  .object({
    bigPictureStep: z.string().default(null),
    thinking: z.string().default(null),
    steps: z
      .array(
        z.union([
          ExistingFileModification,
          NewFileModification,
          TerminalCommandModification,
        ]),
      )
      .default(null),
    searchQuery: z.union([z.string(), z.null()]).default(null),
  })
  .strict();
export type GroupedStepsType = z.infer<typeof GroupedSteps>;

/**
 *
 * Note: files.SelectionContextResult has 2 fields from here for modification shortcircuiting.
 *
 */
export const ModificationsPlan = z
  .object({
    thinking: z.string().default(null),
    draftBigPictureSteps: z.array(DraftStep).default(null),
    shortAnalysis: z.string().default(null),
    refinedSteps: z.array(GroupedSteps).default(null),
    modifiedUrls: z.array(z.string()).default(null),
    tagline: z.string().default(null),
    summary: z.string().default(null),
  })
  .strict();
export type ModificationsPlanType = z.infer<typeof ModificationsPlan>;

export const ShortCircuitAction = z
  .object({
    action: ActionToPerform,
    askClarifyingQuestions: z.boolean(),
    modificationsPlan: z.union([ModificationsPlan, z.null()]),
  })
  .strict();
export type ShortCircuitActionType = z.infer<typeof ShortCircuitAction>;
