/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const ApiRequest = z
  .object({
    curl: z.string(),
    description: z.string(),
    response: z.string(),
  })
  .strict();
export type ApiRequestType = z.infer<typeof ApiRequest>;

export const SelectedComponent = z
  .object({
    name: z.string(),
    filePath: z.string(),
    lineNumber: z.number().int(),
    changeMessage: z.string(),
  })
  .strict();
export type SelectedComponentType = z.infer<typeof SelectedComponent>;

export const UserInitialMessage = z
  .object({
    message: z.string(),
    apiRequests: z.array(ApiRequest),
    selectedComponents: z.array(SelectedComponent),
  })
  .strict();
export type UserInitialMessageType = z.infer<typeof UserInitialMessage>;

export const UnansweredQuestions = z
  .object({
    questions: z.array(z.string()),
  })
  .strict();
export type UnansweredQuestionsType = z.infer<typeof UnansweredQuestions>;

export const AnsweredQuestions = z
  .object({
    questions: z.array(z.record(z.string(), z.string())),
  })
  .strict();
export type AnsweredQuestionsType = z.infer<typeof AnsweredQuestions>;

export const SimpleMessage = z
  .object({
    message: z.string(),
  })
  .strict();
export type SimpleMessageType = z.infer<typeof SimpleMessage>;

export const ChatMessage = z
  .object({
    role: ChatMessageRole,
    messageType: ChatMessageType,
    message: z.union([UnansweredQuestions, AnsweredQuestions, SimpleMessage]),
  })
  .strict();
export type ChatMessageType = z.infer<typeof ChatMessage>;
