/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const SelectedComponent = z
  .object({
    name: z.string(),
    filePath: z.string(),
    lineNumber: z.number().int(),
    changeMessage: z.string(),
  })
  .strict();
export type SelectedComponentType = z.infer<typeof SelectedComponent>;

export const SelectedComponents = z
  .object({
    selectedComponents: z.array(SelectedComponent),
  })
  .strict();
export type SelectedComponentsType = z.infer<typeof SelectedComponents>;

export const FileSearchResult = z
  .object({
    filePath: z.string(),
    content: z.string(),
    totalScore: z.number(),
  })
  .strict();
export type FileSearchResultType = z.infer<typeof FileSearchResult>;

export const ApiRequest = z
  .object({
    curl: z.string(),
    description: z.string(),
    response: z.string(),
  })
  .strict();
export type ApiRequestType = z.infer<typeof ApiRequest>;
