/**
 * NOTE: automatically generated by the pydantic2zod compiler.
 */

import { z } from "zod";

export const RepoSettings = z
  .object({
    packageManager: z.string(),
    port: z.number().int(),
    devCommand: z.string(),
    rootDirectory: z.string(),
    branchName: z.string(),
  })
  .strict();
export type RepoSettingsType = z.infer<typeof RepoSettings>;
