[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -c %(here)s/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:uvicorn]
command=uv run uvicorn src.api:app --host 127.0.0.1 --port %(process_num)s --workers 1 %(ENV_UVICORN_RELOAD)s
process_name=worker_%(process_num)s
numprocs=4
numprocs_start=8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=WORKER_ID="%(process_num)s" 